:toc:
:toc-title: 目次
:icons: font

= SQ Simulator

SQ Simulator は、link:https://www.javada.or.jp/jigyou/gino/sagyou_naiyou.html#b184_010[技能検定 シーケンス制御職種 シーケンス制御作業] の製作等作業試験で使われる「試験用盤」をPC上で再現し、実機無しの試験対策を可能にするシミュレーションツールです。試験対策だけでなく、基礎的なPLCプログラミングの学習にも使用できます。

== 必要ツール

* GT Designer3 (GOT2000)

* 下記のいずれか

** GX Works3

** GX Works2

** MELSECシリーズPLC本体

SQ Simulator は 「GT Designer3 Version1 (GOT2000)」によりGOT2000用プロジェクトファイルとして実装されているため、利用にはGT Designer3 Version1 (GOT2000) が必要です。また、GT Designer3に付属の「GT Simulator3」とPLCプログラムを実行するために、GX Works2/3 に付属の GX Simulator またはMELSECシリーズのPLC本体のいずれかも併せて必要です。

[NOTE]
====
各ソフトウェアは体験版が無償で利用可能です。

* link:[GT Designer3 Version1 (GOT2000)]

* link:[GX Works3]

* link:[GX Works2]
====

== ダウンロード

link:https://github.com/avenue68/sq-simulator/releases[こちら]から最新バージョンの SQ Simulator（`sq-simulator.GTX`）をダウンロードし、解凍してください。サンプル用PLCプログラムも同梱されています。

== 起動方法

各種ツールやPLCの詳細な使用方法は対応する公式マニュアルを参照してください。

. 実行するPLCプログラムを GX Works3 または GX Works2 で開きます。

. 開いたPLCプログラムで GX Simulator を起動するか、PLC に書き込みます。

. `sq-simulator.GTX` ファイルを GT Designer3 (GOT2000) で開きます。

. ユーザー名およびパスワードを求められるので、下記の通り入力します。

** ユーザー名: `user`

** パスワード: `password`

. 使用する GX Simulator または PLC に合わせ、GT Simulator3 の接続先を設定します。

. GT Simulator3 を起動します。

. GT Simulator3 上で SQ Simulator が実行されます。

== 操作方法

=== スタート画面

使用するPLC機種および受験する級を選択し、SQ Simulator の挙動を設定するための画面です。

==== PLC機種

使用するPLCの入出力アドレスが8進の機種（MELSEC-F, MELSEC-IQFなど）か、16進の機種（MELSEC-Q, MELSEC-IQRなど）かを選択します。

==== 試験級種

受験する級を選択します。3級を選択すると制御対象の入出力機器が少なくなります。

[NOTE]
====
詳細は製作等作業試験の問題概要を参照してください。

* https://www.kentei.javada.or.jp/
====

=== 配線画面

PLC入出力ユニットと試験用盤配線用端子台間の配線をシミュレーションするための画面です。試験用盤配線用端子台の各端子番号に対し、PLCの入出力ユニットの端子番号（入出力アドレス）を割り付けていきます。

スタート画面でPLC機種を `16進 I/O` に設定している場合は、入出力ユニットの端子番号に加えて入出力ユニットの先頭X/Y番号も入力してください。

==== デフォルト割付ボタン

デフォルト割付ボタンを押下すると、下記のI/O割付表に従ってPLC入出力ユニットの端子番号が自動入力されます。

[]
|===
|8進 |16進 |試験用盤端子番号 |8進 |16進 |試験用盤端子番号

|X0
|X0
|1
|Y0
|Y0
|20

|X1
|X1
|2
|1
|1
|21

|X2
|X2
|3
|Y2
|Y2
|22

|X3
|X3
|4
|Y3
|Y3
|23

|X4
|X4
|5
|Y4
|Y4
|24

|X5
|X5
|6
|Y5
|Y5
|25

|X6
|X6
|7
|Y6
|Y6
|26

|X7
|X7
|8
|Y7
|Y7
|27

|X10
|X8
|9
|Y10
|Y8
|28

|X11
|X9
|10
|Y11
|Y9
|29

|X12
|XA
|11
|Y12
|YA
|30

|X13
|XB
|12
|Y13
|YB
|31

|X14
|XC
|13
|Y14
|YC
|32

|X15
|XD
|14
|Y15
|YD
|33

|X16
|XE
|15
|-
|-
|-

|X17
|XF
|16
|-
|-
|-
|===

実際の製作等作業試験ではI/O割付表の内容は試験回ごとにランダムに指定されるので、学習内容に応じて使用してください。

==== CP1 サーキットプロテクタ

試験用盤のサーキットプロテクタ兼電源スイッチです。操作画面に遷移する前にCP1をONにしてください。

また、CP1がONのまま入出力ユニット端子番号を変更しようとした場合、警告が表示されます。試験本番では電源が入ったまま配線作業を行うとその時点で不合格になると言われているので、SQ Simulator 使用中もこの警告が表示されないよう注意してください。

=== 操作画面

ボタン操作等により試験用盤を動作させるための画面です。操作画面に遷移したら、GX Simulator / PLC を一度リセットするようにしてください。

==== パレット


==== LS1 - LS5 手動操作用スイッチ

=== 問い合わせ

